[parity]
chain = "classic"
base_path = "/mnt/etc/main"
db_path = "/mnt/etc/main/chains"
keys_path = "/mnt/etc/keys"
identity = ""
light = false
mode = "active"
mode_timeout = 300
mode_alarm = 3600
auto_update = "critical"
release_track = "stable"
public_node = false
no_download = false
no_consensus = false
no_persistent_txqueue = false

[network]
port = 30303
min_peers = 50
max_peers = 100
nat = "any"
id = 1
bootnodes = []
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false
reserved_only = false

[rpc]
disable = false
port = 8545
interface = "all"
cors = []
apis = ["web3", "eth", "pubsub", "personal" ,"net", "parity","signer", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["none"]

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["none"]
apis = ["web3", "eth", "pubsub", "personal","net", "parity", "signer","parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["none"]


[ipfs]
enable = false
port = 5001
interface = "all"
cors = []
hosts = ["none"]

[footprint]
tracing = "auto"
pruning = "auto"
pruning_history = 64
pruning_memory = 32
cache_size_db = 128
cache_size_blocks = 8
cache_size_queue = 40
cache_size_state = 25
cache_size = 1024 # Overrides above caches with total size
fast_and_loose = false
db_compaction = "ssd"
fat_db = "auto"
#scale_verifiers = true
#num_verifiers = 6
[snapshots]
disable_periodic = false


[misc]
# Logs will be stored at /mnt/etc/log/parity.log .
log_file = "/mnt/etc/log/parity.log"